// <auto-generated />
namespace StaticVoid.Blog.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AdminSecurable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdminSecurable));
        
        string IMigrationMetadata.Id
        {
            get { return "201305280453075_AdminSecurable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
