// <auto-generated />
namespace StaticVoid.Blog.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RemovingVisits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovingVisits));
        
        string IMigrationMetadata.Id
        {
            get { return "201307140654324_RemovingVisits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
