// <auto-generated />
namespace StaticVoid.Blog.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PostsToBlogs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostsToBlogs));
        
        string IMigrationMetadata.Id
        {
            get { return "201306011341392_PostsToBlogs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
