// <auto-generated />
namespace StaticVoid.Blog.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NewUserSystem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewUserSystem));
        
        string IMigrationMetadata.Id
        {
            get { return "201505210445127_NewUserSystem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
